runtime: nodejs10

instance_class: F2

env_variables:
  PROTO: "https://"
  FQDN: "pandemicparlour.ue.r.appspot.com"

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301 
