runtime: nodejs10

instance_class: F2

env_variables:
  PROTO: "https://"
  FQDN: "pandemicparlour.ue.r.appspot.com"
  GOOGLE_CLIENT_ID: "236537749378-pulij6j272kd3gcs13hljtu9k9283kht.apps.googleusercontent.com"
  GOOGLE_REDIRECT_PATH: "/auth/google"

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301 
