FROM postgres:12

ENV POSTGRES_MULTIPLE_DATABASES=parlour,parlour_shadow
ENV POSTGRAPHILE_PASSWORD=${POSTGRAPHILE_PASSWORD}
ENV DOCKER_BUILD=1

COPY pg-init-scripts/create-multiple-databases.sh /docker-entrypoint-initdb.d/
COPY pg-init-scripts/roles.sh /docker-entrypoint-initdb.d/