FROM postgres:12

ENV POSTGRES_MULTIPLE_DATABASES=parlour,parlour_shadow
# will need to add a POSTGRES_PASSWORD environment variable to the docker run command

COPY pg-init-scripts/create-multiple-databases.sh /docker-entrypoint-initdb.d/

